var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/contract/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__5c5d63df._.js")
R.c("server/chunks/ssr/_eaf688b1._.js")
R.c("server/chunks/ssr/_b83ccf8c._.js")
R.c("server/chunks/ssr/[root-of-the-server]__f08806e5._.js")
R.c("server/chunks/ssr/[root-of-the-server]__bed7000d._.js")
R.c("server/chunks/ssr/1629d_next_dist_8dc31fba._.js")
R.c("server/chunks/ssr/src_app_5b2047f8._.js")
R.c("server/chunks/ssr/1629d_next_dist_client_components_builtin_global-error_0d5cb623.js")
R.c("server/chunks/ssr/[root-of-the-server]__bf95b460._.js")
R.c("server/chunks/ssr/1629d_next_dist_client_components_b01b33e4._.js")
R.c("server/chunks/ssr/1629d_next_dist_client_components_builtin_forbidden_4cab2078.js")
R.c("server/chunks/ssr/1629d_next_dist_client_components_builtin_unauthorized_b8fbdcad.js")
R.c("server/chunks/ssr/_next-internal_server_app_contract_page_actions_6c3acbe3.js")
R.m(12106)
module.exports=R.m(12106).exports
